name: my_first_flutter
description: my first flutter demo

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

#dependencies:
#  flutter: any
#  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true

dependencies:
  flutter_web_ui: any
  flutter_web: any
  flutter_web_test: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

dependency_overrides:
#  flutter:
#    sdk: flutter
  flutter_web:
    path: G:/flutterSdks/flutter_web/packages/flutter_web
  flutter_web_ui:
    path: G:/flutterSdks/flutter_web/packages/flutter_web_ui
  flutter_web_test:
    path: G:/flutterSdks/flutter_web/packages/flutter_web_test
